// Build script to inject environment variables into config
// This runs during Netlify build and creates firebase-config.js from env vars

const fs = require('fs');

const config = {
    apiKey: process.env.FIREBASE_API_KEY || '',
    authDomain: process.env.FIREBASE_AUTH_DOMAIN || '',
    projectId: process.env.FIREBASE_PROJECT_ID || '',
    storageBucket: process.env.FIREBASE_STORAGE_BUCKET || '',
    messagingSenderId: process.env.FIREBASE_MESSAGING_SENDER_ID || '',
    appId: process.env.FIREBASE_APP_ID || ''
};

const content = `// Auto-generated by build-config.js - DO NOT EDIT
// Configure these values in Netlify Dashboard > Site settings > Environment variables
const firebaseConfig = ${JSON.stringify(config, null, 4)};
`;

fs.writeFileSync('firebase-config.js', content);
console.log('firebase-config.js generated successfully');
